# Generated by Django 5.2.8 on 2025-11-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_adminreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_adminreg',
        ),
    ]
