# Generated by Django 5.2.8 on 2025-11-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_delete_tbl_adminreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_adminreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminreg_name', models.CharField(max_length=40)),
                ('adminreg_Email', models.CharField(max_length=40)),
                ('adminreg_password', models.CharField(max_length=40)),
            ],
        ),
    ]
