# Generated by Django 5.2.8 on 2025-11-27 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_delete_tbl_adminreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_adminreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminReg_name', models.CharField(max_length=40)),
                ('adminReg_Email', models.CharField(max_length=40)),
                ('adminReg_password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
            ],
        ),
    ]
