# Generated by Django 5.2.8 on 2026-03-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
