# Generated by Django 5.2.8 on 2026-01-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_property',
        ),
    ]
