# Generated by Django 5.2.8 on 2026-01-06 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_tbl_subcategory'),
        ('Guest', '0004_delete_tbl_property'),
        ('Seller', '0002_delete_tbl_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50)),
                ('property_Amount', models.IntegerField()),
                ('property_photo', models.FileField(upload_to='Assets/Property/Photo/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_seller')),
            ],
        ),
    ]
