# Generated by Django 5.2.8 on 2026-03-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_tbl_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_content', models.CharField(max_length=200)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=200, null=True)),
                ('complaint_status', models.IntegerField(default=0)),
            ],
        ),
    ]
