# Generated by Django 5.2.8 on 2026-02-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_status',
            field=models.IntegerField(default=0),
        ),
    ]
